# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
    ]
